import { Feather } from '@expo/vector-icons';
import { Link } from 'expo-router';
import { Alert, Pressable, Text, View } from 'react-native';
import { AppShell, SectionTitle } from '@/components/AppShell';
import { StatCard } from '@/components/StatCard';
import { getSeasonStatus, routes, sponsors } from '@/data/mockData';
import { useDemo } from '@/state/DemoContext';

export default function Home() {
  const { hm, trees, repairedTrailMeters, importTrack, checkins, posts } = useDemo();
  const seasonStatus = getSeasonStatus();
  const impactProgress = Math.min(100, Math.round((trees / 500) * 100));
  const handleImport = () => { importTrack(); Alert.alert('GPX-Track importiert', '620 Höhenmeter wurden deinem Saisonkonto gutgeschrieben.'); };
  return <AppShell><View className="mb-8 mt-2 flex-col justify-between gap-6 md:flex-row md:items-end"><View className="max-w-xl"><Text className="mb-3 text-[11px] font-bold uppercase tracking-[3px] text-gold">Dein Berg. Deine Wirkung.</Text><Text className="font-display text-4xl font-bold leading-tight text-ink md:text-6xl">Heute ist ein guter Tag für den Untersberg.</Text><Text className="mt-4 max-w-lg text-base leading-6 text-moss">Sammle Höhenmeter, halte deine Gipfel fest und verwandle jeden Aufstieg in etwas, das bleibt.</Text></View><Link href="/checkin" asChild><Pressable className="flex-row items-center gap-3 self-start rounded-full bg-forest px-5 py-4"><Feather name="map-pin" color="#FAF6EE" size={17} /><Text className="font-bold text-sand">Gipfel Check-In</Text></Pressable></Link></View>
    <View className="mb-8 flex-row gap-3"><StatCard icon="trending-up" value={`${hm.toLocaleString('de-DE')} hm`} label="gegipfelt dieses Jahr" /><StatCard icon="heart" value={`${trees}`} label="Bäume ermöglicht" accent="gold" /><StatCard icon="tool" value={`${repairedTrailMeters} m`} label="Steig saniert" /></View>
    <View className="mb-4 overflow-hidden rounded-3xl bg-forest p-6 md:p-8"><View className="flex-row items-start justify-between"><View className="max-w-md"><Text className="mb-2 text-[11px] font-bold uppercase tracking-[2px] text-gold">Powered by Marktgemeinde Grödig & Alpenverein</Text><Text className="font-display text-2xl font-bold text-sand md:text-3xl">Gemeinsam bleibt der Berg.</Text><Text className="mt-2 leading-5 text-sand/70">{trees} Bäume, {repairedTrailMeters} sanierte Wegmeter und ein Untersberg, der für alle da bleibt.</Text></View><Link href="/sponsoren" asChild><Pressable className="rounded-full bg-gold px-4 py-3"><Text className="text-xs font-bold text-ink">Impact</Text></Pressable></Link></View><View className="mt-6 h-2 overflow-hidden rounded-full bg-sand/20"><View className="h-full rounded-full bg-gold" style={{ width: `${impactProgress}%` }} /></View><View className="mt-3 flex-row justify-between"><Text className="text-xs font-semibold text-sand/60">Klimawald: {trees} Bäume</Text><Text className="text-xs font-semibold text-sand/60">500 Ziel</Text></View></View>
    <View className={`mb-8 flex-row items-start gap-3 rounded-2xl border p-4 ${seasonStatus.active ? 'border-forest/20 bg-forest/5' : 'border-gold/40 bg-gold/10'}`}><Feather name="shield" size={18} color={seasonStatus.active ? '#1E382B' : '#B46A34'} /><View className="flex-1"><Text className="font-bold text-ink">{seasonStatus.label} · {seasonStatus.active ? 'aktiv' : 'außerhalb des Saisonfensters'}</Text><Text className="mt-1 text-sm leading-5 text-moss">Wildschutz: Check-In und Tracking nur von 06:00 bis 20:00 Uhr. So schützen wir Gams- und Rauhfußwild in Dämmerung und Nacht.</Text></View></View>
    <View className="mb-8"><SectionTitle eyebrow="Dein nächster Schritt" title="Mach den Berg sichtbar" /><View className="flex-row flex-wrap gap-3"><Link href="/gipfelbuch" asChild><Pressable className="min-w-[30%] flex-1 rounded-2xl border border-line bg-card p-4"><Feather name="edit-3" size={19} color="#1E382B" /><Text className="mt-5 font-bold text-ink">Gipfelbucheintrag</Text><Text className="mt-1 text-xs text-moss">Deinen Tag teilen</Text></Pressable></Link><Pressable onPress={handleImport} className="min-w-[30%] flex-1 rounded-2xl border border-line bg-card p-4"><Feather name="upload-cloud" size={19} color="#1E382B" /><Text className="mt-5 font-bold text-ink">GPX-Track</Text><Text className="mt-1 text-xs text-moss">{checkins ? 'Track verifiziert' : 'Route importieren'}</Text></Pressable><Link href="/ranking" asChild><Pressable className="min-w-[30%] flex-1 rounded-2xl border border-line bg-card p-4"><Feather name="award" size={19} color="#D9A036" /><Text className="mt-5 font-bold text-ink">Badges</Text><Text className="mt-1 text-xs text-moss">Dein Fortschritt</Text></Pressable></Link></View></View>
    <View className="mb-8"><SectionTitle eyebrow="Untersberg kompakt" title="Vier Wege, unzählige Geschichten" action="Alle Wege" /><View className="flex-row flex-wrap gap-3">{routes.map(route => <Link key={route.name} href="/checkin" asChild><Pressable className="min-w-[45%] flex-1 rounded-2xl border border-line bg-card p-4"><View className="mb-4 h-1 w-10 rounded-full" style={{ backgroundColor: route.color }} /><Text className="font-display text-lg font-bold text-ink">{route.name}</Text><Text className="mt-1 text-xs text-moss">{route.detail}</Text><View className="mt-4 flex-row justify-between"><Text className="text-xs font-bold text-ink">{route.elevation} m</Text><Text className="text-xs text-moss">{route.time}</Text></View></Pressable></Link>)}</View></View>
    <View className="mb-8"><SectionTitle eyebrow="Salzburg trägt Gipfelt" title="Unsere Partner am Berg" action="Alle Partner" /><Link href="/sponsoren" asChild><Pressable className="mb-3 overflow-hidden rounded-3xl bg-card"><View className="flex-row items-start justify-between bg-forest p-5"><View className="flex-1"><Text className="text-[10px] font-bold uppercase tracking-[2px] text-gold">Hauptsponsor · Salzburg AG</Text><Text className="mt-2 font-display text-2xl font-bold text-sand">Klimawald Untersberg</Text><Text className="mt-1 text-sm leading-5 text-sand/65">500 Bäume für 500.000 Höhenmeter.</Text></View><View className="h-12 w-12 items-center justify-center rounded-full bg-gold"><Text className="font-display text-lg font-bold text-forest">SA</Text></View></View><View className="flex-row items-center justify-between px-5 py-4"><Text className="text-xs font-semibold text-moss">320 von 500 Bäumen ermöglicht</Text><View className="flex-row items-center gap-2"><Text className="text-xs font-bold text-forest">Impact ansehen</Text><Feather name="arrow-up-right" size={15} color="#1E382B" /></View></View></Pressable></Link><View className="flex-row gap-3">{sponsors.slice(1).map(sponsor => <Link key={sponsor.name} href="/sponsoren" asChild><Pressable className="min-w-[29%] flex-1 rounded-2xl border border-line bg-card p-4"><View className="mb-4 h-9 w-9 items-center justify-center rounded-full" style={{ backgroundColor: `${sponsor.accent}22` }}><Text className="text-[10px] font-bold" style={{ color: sponsor.accent }}>{sponsor.name.split(' ').map(word => word[0]).join('').slice(0, 2)}</Text></View><Text className="font-bold text-ink">{sponsor.name}</Text><Text className="mt-1 text-xs leading-4 text-moss">{sponsor.campaign}</Text></Pressable></Link>)}</View></View>
    <SectionTitle eyebrow="Aus dem Gipfelbuch" title="Gerade oben" action="Feed öffnen" /><View className="gap-3">{posts.slice(0, 2).map(post => <View key={post.id} className="flex-row items-center gap-3 rounded-2xl border border-line bg-card p-3"><View className="h-11 w-11 items-center justify-center rounded-full bg-forest"><Text className="text-xs font-bold text-gold">{post.initials}</Text></View><View className="flex-1"><Text className="font-bold text-ink">{post.user} <Text className="font-normal text-moss">auf {post.summit}</Text></Text><Text className="mt-1 text-xs text-moss">{post.elevation} hm · {post.duration} · {post.kudos} Bergheil!</Text></View><Feather name="chevron-right" color="#718B73" size={18} /></View>)}</View>
  </AppShell>; }
