import { Feather } from '@expo/vector-icons';
import { Text, View } from 'react-native';
import { AppShell, SectionTitle } from '@/components/AppShell';
import { sponsors } from '@/data/mockData';
import { useDemo } from '@/state/DemoContext';

export default function Sponsoren() {
  const { trees, repairedTrailMeters } = useDemo();
  return <AppShell><View className="mb-8"><Text className="mb-2 text-[11px] font-bold uppercase tracking-[2px] text-gold">Impact Portal · Grödig & Untersberg</Text><Text className="font-display text-4xl font-bold text-ink">Was dein Aufstieg bewegt.</Text><Text className="mt-3 max-w-xl text-base leading-6 text-moss">Transparenz vom Einstieg in Glanegg bis zum Gipfel. Unsere regionalen Partner machen aus Höhenmetern konkrete Hilfe für Natur, Wege und Menschen.</Text></View>
    <View className="mb-8 flex-row flex-wrap gap-3"><View className="min-w-[30%] flex-1 rounded-3xl bg-forest p-5"><Feather name="heart" size={20} color="#D9A036" /><Text className="mt-5 font-display text-3xl font-bold text-sand">{trees}</Text><Text className="mt-1 text-xs text-sand/60">Bäume ermöglicht</Text></View><View className="min-w-[30%] flex-1 rounded-3xl bg-card p-5"><Feather name="tool" size={20} color="#1E382B" /><Text className="mt-5 font-display text-3xl font-bold text-ink">{repairedTrailMeters} m</Text><Text className="mt-1 text-xs text-moss">Steig saniert</Text></View><View className="min-w-[30%] flex-1 rounded-3xl bg-card p-5"><Feather name="shield" size={20} color="#718B73" /><Text className="mt-5 font-display text-3xl font-bold text-ink">4</Text><Text className="mt-1 text-xs text-moss">Wildschutz-Tafeln geplant</Text></View></View>
    <SectionTitle eyebrow="Salzburg verbunden" title="Aktive Kampagnen" /><View className="gap-4">{sponsors.map(sponsor => <View key={sponsor.name} className="rounded-3xl border border-line bg-card p-5"><View className="flex-row items-start justify-between"><View className="flex-1"><View className="mb-2 flex-row items-center gap-2"><View className="h-2 w-2 rounded-full" style={{ backgroundColor: sponsor.accent }} /><Text className="text-xs font-bold uppercase tracking-wider text-moss">{sponsor.label}</Text></View><Text className="font-display text-2xl font-bold text-ink">{sponsor.campaign}</Text><Text className="mt-2 text-sm leading-5 text-moss">{sponsor.name} · {sponsor.description}</Text></View><Text className="font-bold text-forest">{sponsor.progress}%</Text></View><View className="mt-5 h-2 overflow-hidden rounded-full bg-sand"><View className="h-full rounded-full" style={{ width: `${sponsor.progress}%`, backgroundColor: sponsor.accent }} /></View><View className="mt-2 flex-row justify-between"><Text className="text-xs font-semibold text-moss">Fortschritt</Text><Text className="text-xs font-bold text-ink">{sponsor.current}</Text></View></View>)}</View>
    <View className="mt-8 rounded-3xl border border-gold/40 bg-gold/10 p-5"><View className="flex-row gap-3"><Feather name="info" size={18} color="#B46A34" /><View className="flex-1"><Text className="font-bold text-ink">Regionales Wirkungsversprechen</Text><Text className="mt-1 text-sm leading-5 text-moss">Jeder verifizierte Aufstieg bleibt in der Region: für saubere Einstiege in Grödig, sichere Steige, naturnahe Wildruhezonen und einen lebendigen Untersberg.</Text></View></View></View>
  </AppShell>;
}
